
const espaniol = {
  // Pantalla inicial
  saludoInicial: 'Hola',
  mensajeRecuperandoDatos: 'Estoy recuperando tus datos...',
  // Navegador
  navegadorEvaluacion: 'Evaluación',
  navegadorNombreApp: 'Non Queue',
  navegadorRegistro: 'Registro',
  navegadorLobby: 'Non Queue',
  navegadorCentro: 'Centro de atención',
  navegadorTurno: 'Turno',
  navegadorTurnoAgendado: 'Turno agendado',
  // Menú lateral
  menuLateralMisTurnos: 'Mis turnos',
  menuLateralEstiloClaro: 'Estilo claro',
  menuLateralEstiloOscuro: 'Estilo oscuro',
  menuLateralCerrarSesion: 'Cerrar sesión',
  // Diálogo emergente
  dialogoEmergenteSi: 'Sí',
  dialogoEmergenteMasTarde: 'Más tarde',
  // Login
  loginEmail: 'Email',
  loginContrasenia: 'Contraseña',
  loginBotonIngresar: 'Ingresar',
  loginBotonRegistrarse: 'Registrarse',
  // Registro
  registroEmail: 'Email',
  registroContrasenia: 'Contraseña',
  registroNombre: 'Nombre',
  registroApellido: 'Apellido',
  registroDni: 'DNI',
  registroBotonRegistrarse: 'Registrarme',
  registroBotonComenzar: 'Comenzar',
  registroMensajeRegistroCompleto: '¡Ha completado el registro!',
  registroMensajeEmpezarUso: 'Ya puede comenzar a pedir turnos...',
  registroDatoRequerido: 'Dato requerido.',
  registroEmailYaRegistrado: 'Email ya registrado.',
  registroDniYaRegistrado: 'DNI ya registrado.',
  registroNoPuedeContenerEspacios: 'No puede contener espacios.',
  registroMinimoOchoCaracteres: 'Debe tener al menos 8 caracteres.',
  registroMinimoTresCaracteres: 'Debe tener al menos 3 caracteres.',
  // Lobby
  lobbyMensajeSacarTurno: 'Sacar turno para:',
  lobbyTurnosFila: 'Turnos para filas',
  lobbyTurnosAgendados: 'Turnos agendados',
  lobbyEnElLugar: 'En el lugar',
  lobbyEsperando: 'Esperando',
  lobbyFecha: 'Fecha',
  lobbyHora: 'Horario',
  lobbyNoHayTurnosFila: 'No hay turnos para filas',
  lobbyNoHayTurnosAgendados: 'No hay turnos agendados',
  // Tipo turnos
  tipoTurnoTurnosFila: 'Fila virtual',
  tipoTurnoTurnosAgendados: 'Turno agendado',
  // Centro
  centroSeleccionarCategoria: 'Seleccione una categoría por favor',
  centroSeleccionarTipoTurno: '¿Qué tipo de turno desea solicitar?',
  centroSeleccionarFechaHora: 'Seleccione fecha y horario del turno',
  centroConfirmacion: 'Confirmación',
  centroCancelar: 'Cancelar',
  centroUnTurnoAntes: 'Hay 1 turno antes del suyo.',
  centroHay: 'Hay',
  centroTurnosAntes: 'turnos antes del suyo.',
  centroNoHayTurnosAntes: 'No hay ningún turno antes del suyo.',
  centroDemoraEstimada: 'La demora estimada es de',
  centroMinutos: 'minutos',
  centroDeseaTomarTurno: '¿Desea tomar el turno?',
  centroSi: 'Sí',
  // Calendario
  calendarioCultura: 'es',
  calendarioCancelar: 'Cancelar',
  // Turnos disponibles
  turnosDisponiblesFechaElegida: 'Fecha elegida',
  turnosDisponiblesCambiarFecha: 'Cambiar fecha',
  turnosDisponiblesHorarios: 'Horarios',
  turnosDisponiblesConfirmar: 'Confirmar',
  turnosDisponiblesCambiarTurno: 'Cambiar horario',
  turnosDisponiblesCancelar: 'Cancelar',
  turnosDisponiblesFecha: 'Fecha',
  turnosDisponiblesHorario: 'Horario',
  turnosDisponiblesMensajeTituloConfirmacion: 'Confirmar turno',
  turnosDisponiblesMensajeConfirmacion: '¿Desea agendar el turno?',
  // Turno
  turnoYaEstoyAqui: 'Ya estoy en el lugar',
  turnoCancelar: 'Cancelar turno',
  turnoBienvenida: '¡Bienvenida/o!',
  turnoMensajeArrivo1: 'Ya hemos recibido la notificación de su llegada.',
  turnoMensajeArrivo2: 'Su turno aparecerá en pantalla y será atendido/a.',
  turnoCancelado: 'Su turno ha sido cancelado.',
  turnoUnaPersonaEnLugar: '1 persona con turno ya está en el lugar.',
  turnoPersonasConTurno: 'personas con turno ya están en el lugar.',
  turnoNingunaPersonaConTurno: 'Ninguna persona con turno está aún en el lugar.',
  turnoUnTurnoAntes: 'Hay 1 turno antes del suyo.',
  turnoHay: 'Hay',
  turnoTurnosAntes: 'turnos antes del suyo.',
  turnoNoHayTurnosAntes: 'No hay ningún turno antes del suyo.',
  turnoDemoraEstimada: 'La demora estimada es de',
  turnoMinutos: 'minutos',
  // Turno agendado
  turnoAgendadoYaEstoyAqui: 'Ya estoy en el lugar',
  turnoAgendadoCancelar: 'Cancelar turno',
  turnoAgendadoMensajeArrivo1: 'Ya hemos recibido la notificación de su llegada.',
  turnoAgendadoMensajeArrivo2: 'Su turno aparecerá en pantalla y será atendido/a.',
  turnoAgendadoCancelado: 'Su turno ha sido cancelado.',
  turnoAgendadoBienvenida: '¡Bienvenida/o!',
  turnoSuTurnoEs: 'Su turno es el',
  turnoALas: 'a las',
  turnoRecordatorio: 'Recuerde estar en el lugar al menos 15 minutos antes del horario.',
  // Evaluación
  evaluacionPedido: 'Por favor evalúe nuestra atención. Nos permite mejorar el servicio.',
  evaluacionSaludo: 'Muchas gracias, que tenga un buen día.',
};

const english = {
  // Pantalla inicial
  saludoInicial: 'Hi',
  mensajeRecuperandoDatos: 'I am recovering your information...',
  // Navegador
  navegadorEvaluacion: 'Rating',
  navegadorNombreApp: 'Non Queue',
  navegadorRegistro: 'Register',
  navegadorLobby: 'Non Queue',
  navegadorCentro: 'Center',
  navegadorTurno: 'Ticket',
  navegadorTurnoAgendado: 'Appointment',
  // Menú lateral
  menuLateralMisTurnos: 'My tickets',
  menuLateralEstiloClaro: 'Dark theme',
  menuLateralEstiloOscuro: 'Light theme',
  menuLateralCerrarSesion: 'Sign out',
  // Diálogo emergente
  dialogoEmergenteSi: 'Yes',
  dialogoEmergenteMasTarde: 'Later',
  // Login
  loginEmail: 'Email',
  loginContrasenia: 'Password',
  loginBotonIngresar: 'Log in',
  loginBotonRegistrarse: 'Sign up',
  // Registro
  registroEmail: 'Email',
  registroContrasenia: 'Password',
  registroNombre: 'Name',
  registroApellido: 'Last name',
  registroDni: 'ID',
  registroBotonRegistrarse: 'Create account',
  registroBotonComenzar: 'Start',
  registroMensajeRegistroCompleto: 'The register has been done correctly!',
  registroMensajeEmpezarUso: 'You can start getting your tickets...',
  registroDatoRequerido: 'Required.',
  registroEmailYaRegistrado: 'Email already registered.',
  registroDniYaRegistrado: 'ID already registered.',
  registroNoPuedeContenerEspacios: 'It cannot contain blanks.',
  registroMinimoOchoCaracteres: 'It must be at least 8 characters long.',
  registroMinimoTresCaracteres: 'It must be at least 3 characters long.',
  // Lobby
  lobbyMensajeSacarTurno: 'Get a ticket for:',
  lobbyTurnosFila: 'Line tickets',
  lobbyTurnosAgendados: 'Appointments',
  lobbyEnElLugar: 'In place',
  lobbyEsperando: 'Waiting',
  lobbyFecha: 'Date',
  lobbyHora: 'Hour',
  lobbyNoHayTurnosFila: 'There are no tickets',
  lobbyNoHayTurnosAgendados: 'There are no appointments',
  // Tipo turnos
  tipoTurnoTurnosFila: 'Virtual line',
  tipoTurnoTurnosAgendados: 'Appointment',
  // Centro
  centroSeleccionarCategoria: 'Please select a category',
  centroSeleccionarTipoTurno: 'Please choose your ticket type',
  centroSeleccionarFechaHora: 'Select the date and time of the appointment',
  centroConfirmacion: 'Confirmation',
  centroCancelar: 'Cancel',
  centroUnTurnoAntes: 'There is 1 ticket before yours.',
  centroHay: 'There are',
  centroTurnosAntes: 'tickets before yours.',
  centroNoHayTurnosAntes: 'There is no ticket before yours.',
  centroDemoraEstimada: 'The estimated delay is',
  centroMinutos: 'minutes',
  centroDeseaTomarTurno: 'Do you want to take this ticket?',
  centroSi: 'Yes',
  // Calendario
  calendarioCultura: 'en',
  calendarioCancelar: 'Cancel',
  // Turnos disponibles
  turnosDisponiblesFechaElegida: 'Chosen date',
  turnosDisponiblesCambiarFecha: 'Change date',
  turnosDisponiblesHorarios: 'Schedules',
  turnosDisponiblesConfirmar: 'Confirm',
  turnosDisponiblesCambiarTurno: 'Change schedule',
  turnosDisponiblesCancelar: 'Cancel',
  turnosDisponiblesFecha: 'Date',
  turnosDisponiblesHorario: 'Schedule',
  turnosDisponiblesMensajeTituloConfirmacion: 'Confirmation',
  turnosDisponiblesMensajeConfirmacion: 'Do you want to schedule this appointment?',
  // Turno
  turnoYaEstoyAqui: 'I\'m in the place',
  turnoCancelar: 'Cancel ticket',
  turnoBienvenida: 'Welcome!',
  turnoMensajeArrivo1: 'We have already received notification of your arrival.',
  turnoMensajeArrivo2: 'Your ticket will appear on the screen and you will be attended.',
  turnoCancelado: 'Your ticket has been canceled.',
  turnoUnaPersonaEnLugar: '1 person in line is already in place.',
  turnoPersonasConTurno: 'persons in line are already in place.',
  turnoNingunaPersonaConTurno: 'No person in line is already in place.',
  turnoUnTurnoAntes: 'There is 1 ticket before yours.',
  turnoHay: 'There are',
  turnoTurnosAntes: 'tickets before yours.',
  turnoNoHayTurnosAntes: 'There is no ticket before yours.',
  turnoDemoraEstimada: 'The estimated delay is',
  turnoMinutos: 'minutes',
  // Turno agendado
  turnoAgendadoYaEstoyAqui: 'I\'m in the place',
  turnoAgendadoCancelar: 'Cancel ticket',
  turnoAgendadoMensajeArrivo1: 'We have already received notification of your arrival.',
  turnoAgendadoMensajeArrivo2: 'Your turn will appear on the screen and you will be attended.',
  turnoAgendadoCancelado: 'Your appointment has been canceled.',
  turnoAgendadoBienvenida: 'Welcome!',
  turnoSuTurnoEs: 'The date of the appointment is',
  turnoALas: 'at',
  turnoRecordatorio: 'Remember to be on site at least 15 minutes before schedule.',
  // Evaluación
  evaluacionPedido: 'Please rate our attention. It allows us to improve the service.',
  evaluacionSaludo: 'Thank you! Have a nice day.',
};

export default { espaniol, english };
